### ISSUE TITLE
Error on current Dart

### ISSUE THREAD

**Issue by dalewking** [damondouglas/random_string.dart#1]
Not sure if you are maintaining this but I tried it in a test and got:

compiler message: file:///Users/dking5/flutter/.pub-cache/hosted/pub.dartlang.org/random_string-0.0.1/lib/random_string.dart:76:35: Error: A value of type 'dart.core::List<dynamic>' can't be assigned to a variable of type 'dart.core::Iterable<dart.core::int>'.
compiler message: Try changing the type of the left hand side, or casting the right hand side to 'dart.core::Iterable<dart.core::int>'.
compiler message:   return new String.fromCharCodes(mergedCodeUnits);
compiler message:                                   ^

**Comment by damondouglas** [comment]
Thank you, @dalewking for pointing this out.  I haven't been working in Dart for a while as my work demands my attention on golang.  Please let me know if you need me to fix this and I'd be happy to.  Welcome to the world of Dart.  It's such a great language!

**Comment by dalewking** [comment]
I just needed some random strings for tests (as I don't believe in using fixed input for tests) but since this didn't work just settled for adding a random number to a string.
