### ISSUE TITLE
randomBetween implementation is wrong

### ISSUE THREAD

**Issue by jamesderlin** [damondouglas/random_string.dart#11]
The current implementation of `randomBetween` (as of 2.0.1) is:

```dart
int randomBetween(int from, int to,
    {AbstractRandomProvider provider = const DefaultRandomProvider()}) {
  if (from > to) throw Exception('$from cannot be > $to');
  var randomDouble = provider.nextDouble();
  if (randomDouble < 0) randomDouble *= -1;
  if (randomDouble > 1) randomDouble = 1 / randomDouble;
  return ((to - from) * provider.nextDouble()).toInt() + from;
}
```

I see a few problems:

* The documentation claims that the returned value should be in the range [`from`, `to`].  As implemented, however, if `from != to`, it can return values only in the range [`from`, `to`).  The `(to - from)` factor should be `(to - from + 1)` to use an inclusive upper-bound.  Consider a simple case of `randomBetween(0, 1)` where you want 2 possible values: Since `toInt()` truncates (rounds to 0), you ultimately want a `double` in the range [0, 2) so that `toInt()` can return an integer in the range [0, 1].  Assuming that `provider.nextDouble()` returns a fraction in the range [0, 1), you therefore must scale it by 2.  Alternatively change the documented behavior. (The existing test to verify that `randomBetween` can return the inclusive upper-bound happens to work because it ends up being a degenerate case.)

* `randomBetween` unnecessarily calls `provider.nextDouble` twice.  It computes an adjusted `randomDouble` value but then proceeds to ignore it.

* I see no documentation from `AbstractRandomProvider` specifying what `nextDouble` should return.  `Random.nextDouble` from `dart:math` returns a value in the range [0, 1), but it's unclear what expectation `AbstractRandomProvider` has.  This is a problem because:

* That `randomBetween` tolerates `provider.nextDouble()` returning `double` values `< 0` or `> 1` suggests that any finite `double` values are legal.  However, that could cause `randomBetween` to return random numbers without a uniform distribution, even if `provider` does have a uniform distribution.  For example, suppose an `AbstractRandomProvider` is given whose `nextDouble` implementation returns a random `double` in the range [0, 100) with a uniform distribution, and suppose that we call `randomBetween(0, 1, provider: myProvider)`.  If `randomDouble` returns a value > 2 (which would happen 98% of the time), the `> 1` check would adjust `randomDouble` to be `< 0.5`.  Assuming that `randomDouble` were used in the final calculation instead of calling `provider.nextDouble()` again, this would give an undue weight to returning 0 instead of 1.  I suggest:

    1. If `provider.nextDouble` returns a value outside the expected range, either fail or retry.  Do *not* try to coerce it into the expected range because doing so is likely to change its distribution.
    2. Document that `AbstractRandomProvider.nextDouble` must return values in the range [0, 1).

**Comment by damondouglas** [comment]
@jamesderlin Thank you for posting this thorough issue.  I will look into this.  Pull requests are also welcome.
