### ISSUE TITLE
alpha numeric  is not evenly distributed

### ISSUE THREAD

**Issue by felix-ht** [damondouglas/random_string.dart#16]
Because you first randomly choose how many characters are numeric and how many are alphanumeric, numerical characters are 4.8 (48/10) times as likely to occur then alphas. This reduces entropy, and thus increases collision probability (the total space of available strings stays the same).

I would actually suggest to move away from the current ascii based approach as this is very easy to get wrong in some minor way and move to charsets as this seems far simpler and thus robust.

this is my current internal implementation:
```dart
const alphaNumericCharSet =
    "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";

String randomAlphaNumeric(int length) =>
    randomStringForCharset(length, alphaNumericCharSet);

String randomStringForCharset(int length, String charset) {
  final random = Random();
  return [
    for (var i = 0; i < length; i++) charset[random.nextInt(charset.length)]
  ].join();
}

```

I could also create a merge request for this

**Comment by damondouglas** [comment]
@felix-ht Thank you so much!  I had a test dependency that did a chi square test for distribution on a different part of the code base.  I removed it to make way for null safety.  I think what I will do is re-introduce the distribution test and have it cover the rest of the codebase.

**Comment by damondouglas** [comment]
@felix-ht do you have data showing your findings that alpha numeric is not evenly distributed?

**Comment by damondouglas** [comment]
I will close this.  Please let me know if you need any further help.
