### ISSUE TITLE
Null-Safety

### ISSUE THREAD

**Issue by LiliBhd** [damondouglas/random_string.dart#17]
Hello,
Will you migrate your package to support null-safety ?

Thanks !

**Comment by damondouglas** [comment]
@LiliBhd I'm under a critical deadline.  I'll definitely attend to this once I get above water.  Thank you for reminding me.  I did the first stage of this here: https://pub.dev/packages/random_string/versions/2.2.0-nullsafety but haven't had a chance to look further into it.

**Comment by damondouglas** [comment]
@LiliBhd and @AntonyLeons thank you both for your help.  I just published the new version and waiting for the "null safe" tag to show up on the pub.dev page before closing this issue.  I ran local checks using `dart migrate` to analyze the code to see if there are any null safe issues and it didn't report any.  Yet, I want to see the "null safe" tag on the pub.dev site to be sure.

**Comment by damondouglas** [comment]
Finally :) 
![Screenshot from 2021-07-15 23-13-59](https://user-images.githubusercontent.com/762456/125901019-9b9db6a9-3b96-4e18-8d09-7c9ac4e99d75.png)
