### ISSUE TITLE
 a suggestion

### ISSUE THREAD

**Issue by loveuqian** [damondouglas/random_string.dart#6]
To reduce the code, you can set a default parameter.

**Comment by damondouglas** [comment]
@loveuqian Thank you for your suggestion.  Pardon, I don't understand what you mean.  Do you have an example?

**Comment by loveuqian** [comment]
i want to call randomNumeric()/randomString() to get a random, without enter numbers

**Comment by damondouglas** [comment]
I think the code is simple enough and a good challenge for a pull request.

**Comment by loveuqian** [comment]
ok

**Comment by damondouglas** [comment]
@loveuqian I'm here if you need me.  请告诉我你要我帮助你。谢谢你。Dart是我的第一的programming language.  加油加油！

**Comment by loveuqian** [comment]
> @loveuqian I'm here if you need me. 请告诉我你要我帮助你。谢谢你。Dart是我的第一的programming language. 加油加油！

thank you
