### ISSUE TITLE
Conflict with Provider package

### ISSUE THREAD

**Issue by lalo-vergel** [damondouglas/random_string.dart#7]
Hi. The Provider package is one of the most popular state management solutions available for Flutter, but we can't use it along with your package because there is a conflict, since you define the same name 'Provider'. In most cases it is not possible to stop using Provider, so we end up unistalling your package. Maybe change it so there are no conflicts in future versions?

Error below:

error: The name 'Provider' is defined in the libraries 'package:provider/src/provider.dart' and 'package:random_string/random_string.dart'. (ambiguous_import at [my_surgery] lib/screens/import_view.dart:124)

Thanks.

**Comment by damondouglas** [comment]
@lalo-vergel Thank you for letting me know and apologies for the trouble.  I'll see what I can do and will look into this tonight (PST time).

**Comment by damondouglas** [comment]
@lalo-vergel Please let me know if anything else is needed. Thank you again for letting me know of this need.
