### ISSUE TITLE
Suggestion: Guaranteed full alpha-numeric character set?

### ISSUE THREAD

**Issue by greg-fischer** [damondouglas/random_string.dart#9]
The randomAlphaNumeric() function doesn't always return a full data set with a minimum of 1 of each possible characters. Basically I want to ensure we get at least 1 of each range: 0-9, a-z, and A-Z.  

 In some cases I was getting only numbers, or only UPPER with numbers.  I've worked around it with the below function, which I'm sure is probably the wrong way to do this, but it works for now.

```    
// Greg Fischer - guaranteed full data set of a-z A-Z and 0-9
String randomAlphaNumericFullSet(int length){
	String x = randomAlphaNumeric(length);
	bool z = false;
	while (z == false) {
		//print('Assessing X: ${x}');
		if(x.contains(new RegExp(r'[a-z]'))
			&& x.contains(new RegExp(r'[A-Z]'))
			&& x.contains(new RegExp(r'[0-9]'))
		){
			// print('contains a-z A-Z and 0-9 : ${x}');
			z = true;
		}
		else {
			x = randomAlphaNumeric(length);
		}
	}
	return x;
}
```

**Comment by damondouglas** [comment]
Hello @greg-fischer thank you so much for this and I never thought of this helpful case.  If I understand you correctly, we want a random generating guaranteeing a representation of alphabet sets, correct?  For example, I imagine, ok machine give me a random string where at least one digit is lower case, one digit is upper case and another is a special character.  Or, more generally, give me a random string where at least 3 characters are numbers, 2 are lower case and 5 are upper case, etc.  I have an idea how to implement this cleanly but just wanted to see first if my thoughts were aligned with yours.  Thank you again for your idea here.

**Comment by greg-fischer** [comment]
Yes, in a way that's what I want. Basically, I want to ensure I'm using all of the desired characters by using at least 1 of every type in the set.  Ideally yes, having a better mix would be nice.  In my case I typically wish to provide a unique key or token.  I sometimes want alpha-numeric only, other times I also want special characters.  It ensures the characters used are 62 possible (a-z, A-Z, 0-9) rather than 36 (A-Z and 0-9).  It would be nice to have the option of either though, but in reality if I wanted only upper, that's super easy after the fact.

While I'm asking...
Another thing that I've ran into before is the need to provide "work safe" random characters. I've ran into a few that generated curse words and ended up in customer hands.  It would be nice to have an optional argument to provide a work safe version. Below is what I found per Microsoft suggestion, and in my old PHP code we do this. So and optional "safe" = true.  randomAlphaNumeric(safe: true);

```
Return only WORK SAFE character output by omitting certain characters and vowels
OMIT Per Microsoft: 0 1 2 5   A E I O U   L N S Z

```

Also, there may be times it could be helpful to get a random string with a provided character set as an argument.  For example, if I wanted to get a random string with only 12345 and ABCD characters.  So I could call the function: randomStringWithSet(characters: '12345ABCD')

Thanks for helping with this!

**Comment by damondouglas** [comment]
Hello @greg-fischer Just writing to let you know I haven't forgotten.  I'm giving a talk next week and once finished, I'll be able to look into this more.  I hope all is well.

**Comment by greg-fischer** [comment]
Oh no problem at all, and don't go out of your way.  I'm using that sample function for the time being anyway and whenever you happen to fit it into your project work is great.  The update is appreciated though!

**Comment by damondouglas** [comment]
@greg-fischer  Thank you for your patience.  I've recovered from my talk finally :).  I'd like to get your feedback on the following to see if this would be helpful.

### Return a full data set with a minimum of 1 of each possible characters.
Perhaps the following function might solve this by adding a `String alphabet` parameter:

```dart
String randomFrom(int length, String alphabet, 
        {AbstractRandomProvider provider: const DefaultRandomProvider()}
    ) 
    { ... }
``` 

By doing this, then we could fulfill the use case above as:

```dart
const NUMERIC = "0123456789"
const UPPER = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
const LOWER = "abcdefghijklmnopqrstuvwxyz"
const ALPHA = "..." // combined UPPER and LOWER
const ALPHA_NUMERIC = "..." // combine everything
String numberPart = randomFrom(2, NUMERIC);
String lowerPart = randomFrom(5, LOWER)
String upperPart = randomFrom(5, UPPER)
```

The existing functions would then be special cases of the `randomFrom` function.

### Combining generated sets

Combining without reshuffling is probably a trivial concatenation of the generated random strings.  However, there are situations where we want to shuffle the combined strings.  Perhaps the following could be included in the library for convenience.

```dart
String combine(Iterable<String> elements, {AbstractRandomProvider provider = ...}) { ... }
```

If order matters, then one could simply concatenate strings as follows.

```dart
String alphaPart = randomAlpha(...)
String mixPart1 = randomFrom(...)
String mixPart2 = randomFrom(...)
String generated = alphaPart + combine([mixPart1, mixPart2]);
```

### Validated or "work safe"

As to the work safe or validated generated strings, would the following work?  It would return a future because we do not know how long this would take given the restrictions placed by the validators.  I have been meaning to provide an async generator anyway.

```dart
class Generator {
    Generator(Iterable<RegExp> validators);
    Future<String> randomFrom(int length, String alphabet, {AbstractRandomProvider ...})
}
```

**Comment by damondouglas** [comment]
@greg-fischer I will close this issue for now.  Please feel free to open it if you still feel this is valuable.  If anyone else reading this feels they'd like to re-open this, please feel free as well.  Thank you, again, for your contribution.

**Comment by greg-fischer** [comment]
I'm so sorry I never did get back to you on this. I haven't done much in dart/flutter in weeks and have had so many other things to deal with. (mainly php dev and sys admin taking priority right now)  From initial review I think this is helpful. I really appreciate you taking time to help with this.  When we get back into the flutter work I'll definitely test this.  Thanks again!

**Comment by damondouglas** [comment]
Hello @greg-fischer Thank you for writing back so quickly.  I've reopen this and will be happy to implement this in time.  I hope you and your family stay safe.
